version: "3"
services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ambass
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33066:3306"
    volumes:
      - .dbdata:/var/lib/mysql
